name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      
      #for adder
      - name: Building adder "ğŸ’¡"
        run:  cargo build -p "adder" 
      - name: Testing Enclave "ğŸ–¥ï¸"
        run: cargo test -p "adder"
      #for subtract
      - name: Building subtract "ğŸ’¡"
        run:  cargo build -p "subtract" 
      - name: Testing Enclave "ğŸ–¥ï¸"
        run: cargo test -p "subtract"
      #for multiplyer
      - name: Building multiplyer "ğŸ’¡"
        run:  cargo build -p "multiplyer" 
      - name: Testing Enclave "ğŸ–¥ï¸"
        run: cargo test -p "multiplyer"

